version: '3.9'

services:
  #Backend
  pharma.api:
    image: ${DOCKER_REGISTRY-}pharma.api
    container_name: pharma.api
    volumes:
      - ./shared/blockchain:/app/shared/blockchain
    build:
      context: .
      dockerfile: ./backend/api/PharmaBlockchainBackend.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      pharma.infrastructure:
        condition: service_healthy
     

  #Databases
  pharma.infrastructure:
    image: postgres:latest
    container_name: pharma.infrastructure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apiDb
    volumes:
      - ./.containers/db:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  #pgAdmin
  pharma.pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    volumes:
      - ./.containers/pgadmin:/var/lib/pgadmin 
      - ./shared/blockchain:/app/shared/blockchain
    depends_on:
      - pharma.infrastructure

  pharma.blockchain:
    container_name: pharma.blockchain
    build:
      context: ./backend/blockchain
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
    - ./backend/blockchain:/app
    ports:
    - "8545:8545"

        
  
