version: '3.9'

services:
  #Backend
  pharma.api:
    image: ${DOCKER_REGISTRY-}pharma.api
    container_name: pharma.api
    build:
      context: .
      dockerfile: ./backend/api/PharmaBlockchainBackend.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      pharma.infrastructure:
        condition: service_healthy

  #Databases
  pharma.infrastructure:
    image: postgres:latest
    container_name: pharma.infrastructure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apiDb
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10